# Required Setup
CONSUMER_TYPE = "spontaneous"

# Section used specifically for Metadata Pvs
[METADATA]

    [METADATA.CA]
    X = "x"
    Y = "y"

    [METADATA.PVA]

# Section specifically for ROI PVs
[ROI]

    [ROI.ROI1]
    MIN_X = "8idEiger4m:ROI1:MinX"
    MIN_Y = "8idEiger4m:ROI1:MinY"
    SIZE_X = "8idEiger4m:ROI1:SizeX"
    SIZE_Y = "8idEiger4m:ROI1:SizeY"

    [ROI.ROI2]
    MIN_X = "8idEiger4m:ROI2:MinX"
    MIN_Y = "8idEiger4m:ROI2:MinY"
    SIZE_X = "8idEiger4m:ROI2:SizeX"
    SIZE_Y = "8idEiger4m:ROI2:SizeY"

    [ROI.ROI3]
    MIN_X = "8idEiger4m:ROI3:MinX"
    MIN_Y = "8idEiger4m:ROI3:MinY"
    SIZE_X = "8idEiger4m:ROI3:SizeX"
    SIZE_Y = "8idEiger4m:ROI3:SizeY"

    [ROI.ROI4]
    MIN_X = "8idEiger4m:ROI4:MinX"
    MIN_Y = "8idEiger4m:ROI4:MinY"
    SIZE_X = "8idEiger4m:ROI4:SizeX"
    SIZE_Y = "8idEiger4m:ROI4:SizeY"

[STATS]

[STATS.STATS1]
    TOTAL = "8idEiger4m:Stats1:Total_RBV"
    MIN = "8idEiger4m:Stats1:MinValue_RBV"
    MAX = "8idEiger4m:Stats1:MaxValue_RBV"
    SIGMA = "8idEiger4m:Stats1:Sigma_RBV"
    MEAN = "8idEiger4m:Stats1:MeanValue_RBV"

    [STATS.STATS4]
    TOTAL = "8idEiger4m:Stats4:Total_RBV"
    MIN = "8idEiger4m:Stats4:MinValue_RBV"
    MAX = "8idEiger4m:Stats4:MaxValue_RBV"
    SIGMA = "8idEiger4m:Stats4:Sigma_RBV"
    MEAN = "8idEiger4m:Stats4:MeanValue_RBV"



